export const CONSTANTS = {
  LLM: {
    PROVIDERS: {
      OPENAI: "openai",
      OLLAMA: "ollama",
    },

    DEFAULT_PROVIDER: "openai",
  },

  OPENAI: {
    DEFAULT_MODEL: "gpt-5-mini",
  },

  OLLAMA: {
    DEFAULT_BASE_URL: "http://localhost:11434",
    DEFAULT_MODEL: "qwen3:8b",
    CHAT_ENDPOINT: "/api/chat",
    REQUEST_TIMEOUT_MS: 120_000,
  },

  JOB_SEARCH: {
    DEFAULT_PAGES_PER_SOURCE: 1,
  },

  ERROR_CODES: {
    INVALID_INPUT: "INVALID_INPUT",
    UNSUPPORTED_LLM_PROVIDER: "UNSUPPORTED_LLM_PROVIDER",
    LLM_PROVIDER_FAILURE: "LLM_PROVIDER_FAILURE",
    INVALID_MODEL_RESPONSE: "INVALID_MODEL_RESPONSE",
    SEARCH_INITIALIZATION_FAILED: "SEARCH_INITIALIZATION_FAILED",
  },
} as const;