export const CONSTANTS = {
  LLM: {
    PROVIDERS: {
      OPENAI: "openai",
      OLLAMA: "ollama",
      GEMINI: "gemini",
    },

    PROVIDER_LABELS: {
      OPENAI: "OpenAI",
      OLLAMA: "Ollama",
      GEMINI: "Gemini",
    },

    DEFAULT_PROVIDER: "openai",
    AVAILABILITY_TIMEOUT_MS: 3_000,
  },

  OPENAI: {
    DEFAULT_MODEL: "gpt-5-mini",
  },

  GEMINI: {
    DEFAULT_MODEL: "gemini-3.5-flash",
  },

  OLLAMA: {
    DEFAULT_BASE_URL: "http://localhost:11434",
    DEFAULT_MODEL: "qwen3:8b",
    CHAT_ENDPOINT: "/api/chat",
    TAGS_ENDPOINT: "/api/tags",
    REQUEST_TIMEOUT_MS: 120_000,
  },

  JOB_SEARCH: {
    DEFAULT_PAGES_PER_SOURCE: 1,
  },

  ERROR_CODES: {
    INVALID_INPUT: "INVALID_INPUT",
    UNSUPPORTED_LLM_PROVIDER: "UNSUPPORTED_LLM_PROVIDER",
    LLM_PROVIDER_FAILURE: "LLM_PROVIDER_FAILURE",
    INVALID_MODEL_RESPONSE: "INVALID_MODEL_RESPONSE",
    SEARCH_INITIALIZATION_FAILED: "SEARCH_INITIALIZATION_FAILED",
    PROVIDER_DISCOVERY_FAILED: "PROVIDER_DISCOVERY_FAILED",
  },
} as const;